from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import random
import logging

# In a production app, we would use sentence-transformers or LangChain to
# evaluate the LLM response against context or prompt mathematically.
# For this MVP, we will simulate a score based on a simple heuristic or random chance
# to demonstrate the architectural data flow.

app = FastAPI(title="Hallucination Detection Service")

class TraceInput(BaseModel):
    prompt: str
    response: str
    context: str | None = None

class ScoreResponse(BaseModel):
    hallucination_score: int
    confidence: float
    explanation: str

@app.get("/health")
def health_check():
    return {"status": "ok"}

@app.post("/api/v1/score", response_model=ScoreResponse)
def compute_hallucination_score(trace: TraceInput):
    try:
        # Mock calculation:
        # normally we'd compare semantic similarity of `response` to `context`
        # Here we randomly assign a score so we can test the alerting threshold

        # If response is way too short, it's rarely a complex hallucination (just a guess for mock logic)
        base_score = random.randint(0, 100)

        # Give higher chance of hallucination if 'ignore previous instructions' is found
        if "ignore" in trace.prompt.lower():
            base_score = min(100, base_score + 40)

        explanation = "Score generated by semantic similarity heuristics."
        if base_score > 70:
            explanation = "High risk of hallucination detected due to low contextual grounding."

        return ScoreResponse(
            hallucination_score=base_score,
            confidence=round(random.uniform(0.7, 0.99), 2),
            explanation=explanation
        )

    except Exception as e:
        logging.error(f"Error computing score: {e}")
        raise HTTPException(status_code=500, detail="Internal server error")
